### PR TITLE
Support wechat notification

### PR DESCRIPTION
**Pull request by DasyDong**
In china we use wechat at most, so I add wechat notification

### CODE REVIEW

**Comment by DasyDong** [comment]
Hello @egeland and @mumoshu, is it possible to review and merge this pr?

**Comment by DasyDong** [comment]
@matthope  Sure,  i have changed readme,  is that ok ?

**Comment by DasyDong** [comment]
@matthope 

> @matthope Updated, thanks a lot
Hi matthope ,did i miss something？is the pr ready to merge ?

**Comment by matthope** [comment]
Heya @DasyDong  - Please be aware of the points raised in https://github.com/kube-aws/kube-spot-termination-notice-handler/issues/36

**Comment by DasyDong** [comment]
> Heya @DasyDong - Please be aware of the points raised in #36

got it ! I am  also contributed in AWS node termination handler , seems that notification about more ways may not be merged  in the short time ,  maybe in future

**Pull request merged**
